const buildDistrictOptions = (districts) => districts.map((district) => ({
  value: district,
  label: district,
}));

export const ugandaRegions = [
  {
    value: "Central Region",
    label: "Central Region",
    description: "Kampala, Wakiso, Mukono, Masaka, and the wider Buganda belt.",
    accent: "from-orange-500 via-orange-400 to-amber-300",
    districts: buildDistrictOptions([
      "Buikwe",
      "Bukomansimbi",
      "Butambala",
      "Buvuma",
      "Gomba",
      "Kalangala",
      "Kalungu",
      "Kampala",
      "Kasanda",
      "Kayunga",
      "Kiboga",
      "Kyankwanzi",
      "Kyotera",
      "Luweero",
      "Lwengo",
      "Lyantonde",
      "Masaka",
      "Mityana",
      "Mpigi",
      "Mubende",
      "Mukono",
      "Nakaseke",
      "Nakasongola",
      "Rakai",
      "Sembabule",
      "Wakiso",
    ]),
  },
  {
    value: "Eastern Region",
    label: "Eastern Region",
    description: "Busoga, Bukedi, Bugisu, Teso, and the Karamoja-adjacent districts.",
    accent: "from-sky-500 via-cyan-400 to-emerald-300",
    districts: buildDistrictOptions([
      "Amuria",
      "Budaka",
      "Bududa",
      "Bugiri",
      "Bugweri",
      "Bukedea",
      "Bukwo",
      "Bulambuli",
      "Busia",
      "Butaleja",
      "Butebo",
      "Buyende",
      "Iganga",
      "Jinja",
      "Kalaki",
      "Kaberamaido",
      "Kaliro",
      "Kamuli",
      "Kapchorwa",
      "Kapelebyong",
      "Katakwi",
      "Kibuku",
      "Kumi",
      "Kween",
      "Luuka",
      "Manafwa",
      "Mayuge",
      "Mbale",
      "Namayingo",
      "Namisindwa",
      "Namutumba",
      "Ngora",
      "Pallisa",
      "Serere",
      "Sironko",
      "Soroti",
      "Tororo",
    ]),
  },
  {
    value: "Northern Region",
    label: "Northern Region",
    description: "Acholi, Lango, West Nile, and Karamoja districts.",
    accent: "from-violet-500 via-fuchsia-400 to-pink-300",
    districts: buildDistrictOptions([
      "Abim",
      "Adjumani",
      "Agago",
      "Alebtong",
      "Amolatar",
      "Amudat",
      "Amuru",
      "Apac",
      "Arua",
      "Dokolo",
      "Gulu",
      "Kaabong",
      "Kitgum",
      "Koboko",
      "Kole",
      "Lamwo",
      "Lira",
      "Madi-Okollo",
      "Maracha",
      "Moroto",
      "Moyo",
      "Nabilatuk",
      "Nakapiripirit",
      "Napak",
      "Nebbi",
      "Nwoya",
      "Obongi",
      "Omoro",
      "Otuke",
      "Oyam",
      "Pader",
      "Pakwach",
      "Terego",
      "Yumbe",
      "Zombo",
    ]),
  },
  {
    value: "Western Region",
    label: "Western Region",
    description: "Bunyoro, Toro, Ankole, Kigezi, and the tourism corridor.",
    accent: "from-rose-500 via-orange-400 to-amber-200",
    districts: buildDistrictOptions([
      "Buhweju",
      "Buliisa",
      "Bundibugyo",
      "Bunyangabu",
      "Bushenyi",
      "Hoima",
      "Ibanda",
      "Isingiro",
      "Kabale",
      "Kabarole",
      "Kagadi",
      "Kakumiro",
      "Kamwenge",
      "Kanungu",
      "Kasese",
      "Kazo",
      "Kibaale",
      "Kikuube",
      "Kiruhura",
      "Kiryandongo",
      "Kisoro",
      "Kitagwenda",
      "Mbarara",
      "Mitooma",
      "Ntoroko",
      "Ntungamo",
      "Rukiga",
      "Rukungiri",
      "Rubanda",
      "Rubirizi",
      "Rwampara",
      "Sheema",
      "Masindi",
      "Fort Portal City",
      "Hoima City",
      "Mbarara City",
    ]),
  },
];

export const districtProfiles = {
  Kampala: {
    region: "Central Region",
    capital: "Kampala Central",
    localities: ["Nakasero", "Kololo", "Kisenyi", "Nakawa", "Ntinda", "Makindye"],
    note: "Use landmark-heavy descriptions for apartment blocks, offices, and shopfronts.",
  },
  Wakiso: {
    region: "Central Region",
    capital: "Wakiso",
    localities: ["Entebbe", "Nansana", "Kira", "Kyengera", "Kampala outskirts", "Namayumba"],
    note: "Popular for peri-urban deliveries with multiple settlement clusters.",
  },
  Mukono: {
    region: "Central Region",
    capital: "Mukono",
    localities: ["Seeta", "Namanve", "Katosi", "Kyampisi", "Goma", "Mukono town"],
    note: "Good to include road names and nearby trading centres.",
  },
  Jinja: {
    region: "Eastern Region",
    capital: "Jinja",
    localities: ["Bujagali", "Masese", "Walukuba", "Jinja Central", "Bugembe", "Mpumudde"],
    note: "Add a landmark for estates and industrial plots near the city.",
  },
  Mbale: {
    region: "Eastern Region",
    capital: "Mbale",
    localities: ["Namatala", "Kiwatule", "Boma", "Namakwekwe", "Sesenyi", "Bubulo road"],
    note: "Village, parish, and trading centre names help riders in the hills.",
  },
  Soroti: {
    region: "Eastern Region",
    capital: "Soroti",
    localities: ["Soroti town", "Madera", "Asuret", "Pamba", "Matek", "Katine"],
    note: "Include the exact zone or village when sharing outside the city centre.",
  },
  Gulu: {
    region: "Northern Region",
    capital: "Gulu City",
    localities: ["Layibi", "Pece", "Kasubi", "Kanyagoga", "Bobi", "Laroo"],
    note: "Street and landmark names are often the fastest way to confirm the drop-off.",
  },
  Arua: {
    region: "Northern Region",
    capital: "Arua City",
    localities: ["Mvara", "Oli", "Ediofe", "Arua Hill", "Ayivu", "Arivu"],
    note: "Use trading centre names when the village is outside the municipal core.",
  },
  Mbarara: {
    region: "Western Region",
    capital: "Mbarara City",
    localities: ["Katete", "Kamukuzi", "Kakoba", "Bwizibwera", "Nyamitanga", "Biharwe"],
    note: "A parish or village name helps a lot around growing city edges.",
  },
  Kasese: {
    region: "Western Region",
    capital: "Kasese",
    localities: ["Kilembe", "Nyakasanga", "Rukoki", "Bwera", "Hima", "Kisinga"],
    note: "Useful for both mountain and plain-side deliveries.",
  },
};

export const getRegionMeta = (regionValue) => (
  ugandaRegions.find((region) => region.value === regionValue) || ugandaRegions[0]
);

export const getDistrictProfile = (district) => (
  districtProfiles[district] || {
    region: "",
    capital: district,
    localities: [
      `${district} town`,
      `${district} trading centre`,
      `${district} central`,
      `${district} main road`,
    ],
    note: "Use the district name plus a nearby landmark or trading centre for accurate delivery.",
  }
);
